#!/usr/bin/env node
/**
 * AAJ — marketing-loops engine
 *
 * Models compounding growth loops, not linear funnels. A loop is growth where
 * the output feeds back as input: users invite users, content attracts users
 * who make content, revenue buys the acquisition that produces more revenue.
 *
 * The one question a funnel never asks and a loop lives or dies on:
 * does one turn of the loop produce MORE than one turn's worth of input?
 * That's the loop factor (k). k >= 1 compounds; k < 1 decays to a ceiling.
 *
 * Modes:
 *   score    — compute the loop factor and amplification for one loop
 *   project  — project users over time given a loop and a paid feed
 *   --demo   — run both on sample data, no arguments
 *   --help   — usage
 *
 * No dependencies. Node 18+.
 */

// --- AAJ arg normalisation ---------------------------------------------------
// Accept bare `demo` / `help` as aliases for `--demo` / `--help`. First-run
// friction: users type `node engine.js demo` and hit a JSON parse error.
// Only these two exact tokens are rewritten, so JSON payloads and named modes
// (design, readout, sample, segments, ...) pass through untouched.
process.argv = process.argv.map((a, i) =>
  i >= 2 && /^(demo|help)$/i.test(a) ? '--' + a.toLowerCase() : a
);
// -----------------------------------------------------------------------------


'use strict';

/* ─────────────────────────────  loop math  ───────────────────────────── */

/**
 * Loop factor k for a referral/viral loop:
 *   k = branches × conversion
 * e.g. each user sends 3 invites, 20% convert → k = 0.6
 *
 * For a general loop expressed as a chain of stage conversions, k is the
 * product of every stage rate times the output-per-completion (branches).
 */
function loopFactor(stages, branches) {
  const conv = stages.reduce((acc, s) => acc * s.rate, 1);
  return conv * branches;
}

/**
 * Steady-state amplification of a decaying loop (k < 1).
 * A cohort of N seed users ultimately yields N / (1 - k) total users,
 * because N + Nk + Nk^2 + ... = N/(1-k). This is the multiplier a
 * sub-viral loop adds on top of paid — the reason a k=0.5 loop still
 * doubles the value of every acquired user.
 */
function amplification(k) {
  if (k >= 1) return Infinity;
  if (k < 0) return NaN;
  return 1 / (1 - k);
}

/**
 * Effective CAC once a loop amplifies paid acquisition.
 * If you pay to acquire a user and each seeded user spins the loop with
 * factor k, effective CAC = paid CAC × (1 - k).
 */
function effectiveCac(paidCac, k) {
  if (k >= 1) return 0;
  return paidCac * (1 - k);
}

/* ─────────────────────────────  projection  ───────────────────────────── */

/**
 * Discrete cohort projection over `periods` loop-cycles.
 * Each period: existing users spin the loop (adding users × k),
 * plus a constant paid feed of `paidPerPeriod` new users.
 *
 * Returns per-period new/total, and flags the compounding regime.
 */
function project(cfg) {
  const k = cfg.k;
  const periods = cfg.periods ?? 12;
  const seed = cfg.seed ?? 0;
  const paid = cfg.paidPerPeriod ?? 0;

  if (typeof k !== 'number' || k < 0) die('project needs a non-negative loop factor "k"');
  if (periods < 1 || periods > 240) die('periods must be between 1 and 240');

  const rows = [];
  let total = seed;
  let lastNew = seed;
  for (let t = 1; t <= periods; t++) {
    const loopNew = lastNew * k;      // users generated by last period's new users
    const newUsers = loopNew + paid;   // plus the paid feed
    total += newUsers;
    rows.push({ period: t, newUsers, loopNew, paid, total });
    lastNew = newUsers;
  }
  return { k, seed, paid, periods, rows, final: total };
}

/* ─────────────────────────────  helpers  ───────────────────────────── */

const fmt = (n) => {
  if (!isFinite(n)) return '∞';
  if (Math.abs(n) >= 1000) return Math.round(n).toLocaleString('en-US');
  if (Number.isInteger(n)) return String(n);
  return n.toFixed(2);
};
const pct = (x) => `${(x * 100).toFixed(1)}%`;
const pad = (s, n) => { s = String(s); return s + ' '.repeat(Math.max(0, n - s.length)); };
const padL = (s, n) => { s = String(s); return ' '.repeat(Math.max(0, n - s.length)) + s; };
function bar(v, max, w = 30) {
  if (max <= 0) return '';
  const f = Math.max(0, Math.min(w, Math.round((v / max) * w)));
  return '█'.repeat(f);
}

function die(msg) {
  console.error(`error: ${msg}\n\nRun --help for usage, or --demo for a worked example.`);
  process.exit(1);
}

/* ─────────────────────────────  loop types  ───────────────────────────── */

// Reference data used only to contextualize a computed k — not fabricated
// benchmarks presented as fact. These are structural descriptions of loop
// archetypes, with the qualitative note that most real loops run sub-viral.
const LOOP_TYPES = {
  viral:      { label: 'Viral / referral', note: 'users invite users; k = invites × accept-rate' },
  content:    { label: 'Content', note: 'users create content that ranks/attracts users who create content' },
  paid:       { label: 'Paid recycling', note: 'revenue funds acquisition that produces revenue; bounded by LTV:CAC' },
  network:    { label: 'Network effects', note: 'each user raises the product\'s value, lifting conversion of the next' },
};

/* ─────────────────────────────  score mode  ───────────────────────────── */

function verdictFor(k) {
  if (k >= 1.0) return { tag: 'VIRAL', line: 'k ≥ 1 — self-sustaining. Every user more than replaces themselves; growth compounds without paid input. Rare and fragile; watch for saturation.' };
  if (k >= 0.5) return { tag: 'STRONG SUB-VIRAL', line: 'k in [0.5, 1) — the loop more than doubles the value of every acquired user. This is where most great growth loops actually live. Feed it with paid and it amplifies hard.' };
  if (k >= 0.2) return { tag: 'CONTRIBUTING', line: 'k in [0.2, 0.5) — a real assist. The loop meaningfully lowers effective CAC but won\'t carry growth alone. Worth improving; don\'t rely on it.' };
  if (k > 0) return { tag: 'WEAK', line: 'k in (0, 0.2) — barely moving. The loop exists but contributes little. Either find the one stage throttling it or treat growth as paid-driven and be honest about it.' };
  return { tag: 'BROKEN', line: 'k = 0 — no loop. One or more stages is zero, so nothing feeds back. This is a funnel, not a loop.' };
}

function score(cfg) {
  const stages = cfg.stages;
  const branches = cfg.branches;
  if (!Array.isArray(stages) || !stages.length) die('score needs "stages": an array of {name, rate} steps in the loop');
  if (typeof branches !== 'number' || branches <= 0) die('score needs "branches": output per loop completion (e.g. invites sent per user)');

  for (const s of stages) {
    if (typeof s.rate !== 'number' || s.rate < 0 || s.rate > 1) {
      die(`stage "${s.name || '?'}" needs a rate between 0 and 1 (got ${s.rate})`);
    }
  }

  const k = loopFactor(stages, branches);
  const amp = amplification(k);
  const v = verdictFor(k);

  // Bottleneck: the stage whose improvement lifts k most in relative terms
  // is the lowest-rate stage (product of rates — the smallest factor dominates).
  const throttle = stages.reduce((lo, s) => (s.rate < lo.rate ? s : lo), stages[0]);

  const out = { k, amplification: amp, verdict: v, stages, branches, throttle,
                loopType: cfg.loopType && LOOP_TYPES[cfg.loopType] ? LOOP_TYPES[cfg.loopType] : null,
                paidCac: cfg.paidCac ?? null };
  if (cfg.paidCac != null) out.effectiveCac = effectiveCac(cfg.paidCac, k);
  return { __score: out };
}

/* ─────────────────────────────  rendering  ───────────────────────────── */

function renderScore(r) {
  const out = [];
  out.push('MARKETING LOOP — SCORE');
  out.push('═'.repeat(58));
  out.push('');
  if (r.loopType) out.push(`Loop type   ${r.loopType.label} — ${r.loopType.note}`);
  out.push('');
  out.push(`LOOP FACTOR k = ${r.k.toFixed(3)}`);
  out.push(`VERDICT       ${r.verdict.tag}`);
  out.push('');
  out.push(`  ${r.verdict.line}`);
  out.push('');

  out.push('THE LOOP');
  out.push(`  ${pad('stage', 24)}${padL('rate', 8)}`);
  for (const s of r.stages) {
    const mark = s === r.throttle ? '  ← throttle' : '';
    out.push(`  ${pad(s.name || '(unnamed)', 24)}${padL(pct(s.rate), 8)}${mark}`);
  }
  out.push(`  ${pad('× output per turn', 24)}${padL(fmt(r.branches), 8)}`);
  out.push('  ' + '─'.repeat(32));
  out.push(`  ${pad('= loop factor k', 24)}${padL(r.k.toFixed(3), 8)}`);
  out.push('');

  out.push('WHAT k BUYS YOU');
  if (isFinite(r.amplification)) {
    out.push(`  Amplification    ${r.amplification.toFixed(2)}×   every seeded user ultimately yields ${r.amplification.toFixed(2)} users`);
    if (r.effectiveCac != null) {
      out.push(`  Effective CAC    ${fmt(r.effectiveCac)}   paid CAC ${fmt(r.paidCac)} × (1 − k)`);
      out.push(`                   the loop pays for ${pct(r.k)} of every acquisition`);
    }
  } else {
    out.push('  Amplification    ∞   the loop is self-sustaining; model saturation, not amplification');
  }
  out.push('');

  out.push('WHERE TO PUSH');
  out.push(`  The throttle is "${r.throttle.name || '(unnamed)'}" at ${pct(r.throttle.rate)}. Because k is the product`);
  out.push('  of every stage rate, the lowest rate caps the whole loop — a 10-point gain');
  out.push('  there lifts k more than a 10-point gain anywhere else. Fix the throttle first.');
  out.push('');

  out.push('WHAT THIS MEANS');
  if (r.k >= 1) {
    out.push('  A true viral loop. The scarce resource is no longer acquisition — it\'s');
    out.push('  capacity and saturation. Model the ceiling and protect the loop mechanic;');
    out.push('  don\'t spend on paid you no longer need.');
  } else if (r.k >= 0.5) {
    out.push('  This is the sweet spot most durable growth actually comes from. The loop');
    out.push('  more than doubles paid acquisition, so every dollar of CAC does the work');
    out.push('  of two-plus. Pour fuel in and improve the throttle; don\'t chase k ≥ 1.');
  } else if (r.k >= 0.2) {
    out.push('  A genuine assist, not an engine. Bank the lower effective CAC, but plan');
    out.push('  growth around paid and treat the loop as leverage on it, not a substitute.');
  } else {
    out.push('  The loop isn\'t carrying weight. Either one stage is throttling everything');
    out.push('  (fix it) or this channel is really a funnel — acquisition in, no feedback.');
    out.push('  Be honest about which, and don\'t model compounding that isn\'t there.');
  }
  return out.join('\n');
}

function renderProject(r) {
  const out = [];
  out.push('MARKETING LOOP — PROJECTION');
  out.push('═'.repeat(58));
  out.push('');
  out.push(`Loop factor k        ${r.k.toFixed(3)}`);
  out.push(`Seed users           ${fmt(r.seed)}`);
  out.push(`Paid feed / period   ${fmt(r.paid)}`);
  out.push(`Periods              ${r.periods}`);
  out.push('');

  const maxTotal = r.final;
  out.push('CUMULATIVE USERS');
  out.push(`  ${pad('period', 8)}${padL('new', 10)}${padL('total', 12)}`);
  // Show every period up to 12, then thin out
  const show = r.rows.filter((row, i) => r.periods <= 14 || i < 6 || i >= r.periods - 3 || (i + 1) % 3 === 0);
  let ellipsisShown = false;
  for (let i = 0; i < r.rows.length; i++) {
    const row = r.rows[i];
    if (show.includes(row)) {
      out.push(`  ${pad(row.period, 8)}${padL(fmt(row.newUsers), 10)}${padL(fmt(row.total), 12)}  ${bar(row.total, maxTotal)}`);
      ellipsisShown = false;
    } else if (!ellipsisShown) {
      out.push(`  ${pad('…', 8)}`);
      ellipsisShown = true;
    }
  }
  out.push('');

  // Decompose the final total: how much came from the loop vs paid alone
  const paidOnly = r.seed + r.paid * r.periods;
  const fromLoop = r.final - paidOnly;
  out.push('WHERE THE GROWTH CAME FROM');
  out.push(`  Paid + seed alone    ${fmt(paidOnly)}`);
  out.push(`  Added by the loop    ${fmt(fromLoop)}`);
  if (paidOnly > 0) {
    const mult = r.final / paidOnly;
    out.push(`  Loop multiplier      ${mult.toFixed(2)}×   the loop turned ${fmt(paidOnly)} into ${fmt(r.final)}`);
  }
  out.push('');

  out.push('WHAT THIS MEANS');
  if (r.k >= 1) {
    out.push('  With k ≥ 1 this curve is exponential and the projection runs away — the');
    out.push('  real limit is saturation, which this model doesn\'t impose. Trust the shape,');
    out.push('  not the final number; add a saturation ceiling before planning against it.');
  } else if (r.k >= 0.5) {
    out.push('  The loop is doing more than half the work. Notice the total far exceeds');
    out.push('  paid-alone — that gap is the compounding you\'d miss modeling this as a');
    out.push('  funnel. Fund the paid feed; the loop multiplies it.');
  } else {
    out.push('  The loop adds a real but bounded lift over paid-alone. Growth here is');
    out.push('  mostly the paid feed; the loop lowers effective cost rather than driving');
    out.push('  the curve. Plan the budget accordingly.');
  }
  return out.join('\n');
}

/* ─────────────────────────────  CLI  ───────────────────────────── */

const HELP = `
AAJ — marketing-loops engine

  node loop-model.js score   '<json>'
  node loop-model.js project '<json>'
  node loop-model.js --demo
  node loop-model.js --help

Models compounding growth LOOPS, not linear funnels. The question a funnel
never asks: does one turn of the loop produce more than one turn's worth of
input? That ratio is the loop factor k. k >= 1 compounds on its own; k < 1
decays to a ceiling but still amplifies paid acquisition.

SCORE — compute k for one loop
  {
    "loopType": "viral",              // viral | content | paid | network (optional, labels only)
    "stages": [                       // the conversion steps of ONE loop turn
      { "name": "user invites",   "rate": 0.40 },
      { "name": "invite opened",  "rate": 0.50 },
      { "name": "signs up",       "rate": 0.30 }
    ],
    "branches": 4,                    // output per completion (e.g. invites sent)
    "paidCac": 80                     // optional — shows effective CAC after the loop
  }
  k = (product of stage rates) × branches.  Above: 0.4×0.5×0.3×4 = 0.24.

PROJECT — project users over time
  {
    "k": 0.5,                         // loop factor (from score, or given)
    "seed": 1000,                     // starting users
    "paidPerPeriod": 500,             // constant paid feed each period
    "periods": 12
  }

Most real loops are sub-viral (k < 1) — and that's fine. A k=0.6 loop makes
every acquired user worth 2.5×. Chasing k >= 1 is usually the wrong goal.
`;

const DEMO_SCORE = {
  loopType: 'viral',
  stages: [
    { name: 'user sends invites', rate: 1.0 },
    { name: 'invite opened',      rate: 0.45 },
    { name: 'clicks through',     rate: 0.35 },
    { name: 'signs up',           rate: 0.40 },
  ],
  branches: 4,
  paidCac: 80,
};

const DEMO_PROJECT = { k: 0.6, seed: 1000, paidPerPeriod: 500, periods: 12 };

function main() {
  const argv = process.argv.slice(2);

  if (argv.length === 0 || argv.includes('--help') || argv.includes('-h')) {
    console.log(HELP.trim());
    return;
  }

  if (argv.includes('--demo')) {
    console.log('▸ DEMO 1 — score mode (compute the loop factor)\n');
    const s = score(DEMO_SCORE).__score;
    console.log(renderScore(s));
    console.log('\n\n▸ DEMO 2 — project mode (compound it over 12 periods)\n');
    console.log(renderProject(project(DEMO_PROJECT)));
    console.log('\n(Demo data. Replace with your real loop stages and paid feed.)');
    return;
  }

  const mode = argv[0];
  const raw = argv[1];
  if (!raw) die(`mode "${mode}" needs a JSON argument. Try --demo to see the shape.`);

  let cfg;
  try { cfg = JSON.parse(raw); }
  catch (e) { die(`could not parse JSON — ${e.message}`); }

  if (mode === 'score') console.log(renderScore(score(cfg).__score));
  else if (mode === 'project') console.log(renderProject(project(cfg)));
  else die(`unknown mode "${mode}". Use score, project, --demo, or --help.`);
}

if (require.main === module) main();

module.exports = {
  score, project, loopFactor, amplification, effectiveCac, verdictFor,
  LOOP_TYPES,
};
